name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_RESUME}}
        password: ${{secrets.DOCKER_RESUME_PASSWORD}}

    - name: Build Docker image
      run: |
        docker build --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}} --build-arg CLERK_SECRET_KEY=${{secrets.CLERK_SECRET_KEY}} --build-arg POSTGRES_PRISMA_URL=${{secrets.POSTGRES_PRISMA_URL}} --build-arg BLOB_READ_WRITE_TOKEN=${{secrets.BLOB_READ_WRITE_TOKEN}} -t sumamakhan/resume-builder:latest .

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: sumamakhan/resume-builder:latest

    - name: Verify Pushed Image
      run: docker pull sumamakhan/resume-builder:latest
